name: 'taichunmin auto-renew-2: fUST'

on:
  workflow_dispatch:
  schedule:
    # timezone: UTC
    # 避開整點時間，因為有可能會有時間上的延誤
    - cron: '6-56/10 * * * *'

env:
  BITFINEX_API_KEY: ${{ secrets.BITFINEX_API_KEY }}
  BITFINEX_API_SECRET: ${{ secrets.BITFINEX_API_SECRET }}
  TELEGRAM_CHAT_ID: '-4119951617'
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

jobs:
  bitfinex:
    # 避免被 fork 的 repository 觸發，請改成自己的 GitHub 帳號
    if: github.repository_owner == 'taichunmin'
    # 這個名字必須跟 repo 的 Environments 名稱一樣
    environment: taichunmin-usdt-1
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      actions: write
    steps:
      - name: Dump GitHub context
        env:
          ACTION_CONTEXT: |
            {
              "env": ${{ toJSON(env) }},
              "github": ${{ toJSON(github) }},
              "inputs": ${{ toJSON(inputs) }},
              "job": ${{ toJSON(job) }},
              "runner": ${{ toJSON(runner) }},
              "secrets": ${{ toJSON(secrets) }},
              "steps": ${{ toJSON(steps) }},
              "vars": ${{ toJSON(vars) }}
            }
        run: echo "$ACTION_CONTEXT" | jq .
      - uses: actions/checkout@v4
      - uses: liskin/gh-workflow-keepalive@v1
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Install dependencies, eslint, and run
        env:
          INPUT_AMOUNT: 0
          # https://api-pub.bitfinex.com/v2/conf/pub:list:currency:margin
          # https://api-pub.bitfinex.com/v2/conf/pub:map:currency:sym
          # https://api-pub.bitfinex.com/v2/conf/pub:map:currency:label
          INPUT_CURRENCY: UST
          INPUT_RANK: 0.8
          INPUT_RATE_MAX: 0.01
          INPUT_RATE_MIN: 0.0001
          # https://docs.google.com/spreadsheets/d/1eJSlFDx5iFM_rMM9mFiPO16x1VhyDReAOeCyLT-bdRA/edit#gid=1058478097
          INPUT_PERIOD: |
            {
              '3': 0.00027397,
              '4': 0.00030822,
              '5': 0.00034247,
              '6': 0.00037671,
              '7': 0.00041096,
              '8': 0.00043053,
              '9': 0.00045010,
              '10': 0.00046967,
              '11': 0.00048924,
              '12': 0.00050881,
              '13': 0.00052838,
              '14': 0.00054795,
              '15': 0.00056751,
              '16': 0.00058708,
              '17': 0.00060665,
              '18': 0.00062622,
              '19': 0.00064579,
              '20': 0.00066536,
              '21': 0.00068493,
              '22': 0.00070015,
              '23': 0.00071537,
              '24': 0.00073059,
              '25': 0.00074581,
              '26': 0.00076104,
              '27': 0.00077626,
              '28': 0.00079148,
              '29': 0.00080670,
              '30': 0.00082192,
            }
        run: |
          set -ex
          yarn > /dev/null 2>&1
          yarn lint
          yarn tsx ./bin/funding-auto-renew-2.ts
